spring:
  application:
    name: flyway-plus
  profiles:
    active: dev
  flyway:
    extension:
      jira:
        enabled: true
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082